"""Alter distance_km column to Numeric

Revision ID: 3846c26707fd
Revises: a998a8d421f7
Create Date: 2025-08-02 18:53:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3846c26707fd'
down_revision: Union[str, None] = 'a998a8d421f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'distance_km',
               existing_type=sa.VARCHAR(), # Assuming previous type was VARCHAR
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'distance_km',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.VARCHAR(), # Reverting to VARCHAR
               existing_nullable=True)
    # ### end Alembic commands ###
