"""make gateway column nullable for cash payments

Revision ID: 49dddc43f3cf
Revises: 3743f59852c0
Create Date: 2025-10-09 13:04:13.923183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '49dddc43f3cf'
down_revision: Union[str, None] = '3743f59852c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('driver_ratings')
    op.alter_column('payments', 'gateway',
               existing_type=postgresql.ENUM('PAYFAST', 'PAYSTACK', name='paymentgateway'),
               nullable=True,
               existing_server_default=sa.text("'PAYFAST'::paymentgateway"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'gateway',
               existing_type=postgresql.ENUM('PAYFAST', 'PAYSTACK', name='paymentgateway'),
               nullable=False,
               existing_server_default=sa.text("'PAYFAST'::paymentgateway"))
    op.create_table('driver_ratings',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('driver_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('order_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], name=op.f('driver_ratings_client_id_fkey')),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.driver_id'], name=op.f('driver_ratings_driver_id_fkey')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('driver_ratings_order_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('driver_ratings_pkey')),
    sa.UniqueConstraint('order_id', name=op.f('_order_client_uc'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
