"""Change order id to UUID type

Revision ID: 4ab1f928c359
Revises: 3846c26707fd
Create Date: 2025-08-03 17:43:51.774705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ab1f928c359'
down_revision: Union[str, None] = '3846c26707fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('orders', 'id',
    #            existing_type=sa.String(),
    #            type_=sa.dialects.postgresql.UUID(as_uuid=True),
    #            existing_nullable=False,
    #            nullable=False,
    #            existing_server_default=sa.text("uuid_generate_v4()"),
    #            using='id::uuid')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('orders', 'id',
    #            existing_type=sa.dialects.postgresql.UUID(as_uuid=True),
    #            type_=sa.String(),
    #            existing_nullable=False,
    #            nullable=False,
    #            existing_server_default=sa.text("uuid_generate_v4()"))
    # ### end Alembic commands ###
