"""Add MapBox fields to Order model

Revision ID: 5a434da22e9b
Revises: da0c9b883986
Create Date: 2025-07-27 20:33:04.018842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a434da22e9b'
down_revision: Union[str, None] = 'da0c9b883986'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('route_geometry', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('estimated_duration', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('orders', sa.Column('estimated_distance', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('orders', sa.Column('calculated_eta', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('route_calculation_timestamp', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('alternative_routes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'alternative_routes')
    op.drop_column('orders', 'route_calculation_timestamp')
    op.drop_column('orders', 'calculated_eta')
    op.drop_column('orders', 'estimated_distance')
    op.drop_column('orders', 'estimated_duration')
    op.drop_column('orders', 'route_geometry')
    # ### end Alembic commands ###
