"""add_order_id_to_driver_ratings

Revision ID: 5e7c65591110
Revises: ca88e4cbf893
Create Date: 2025-10-06 04:58:54.661929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5e7c65591110'
down_revision: Union[str, None] = 'ca88e4cbf893'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driver_ratings', sa.Column('order_id', sa.String(), nullable=False))
    op.create_foreign_key(op.f('driver_ratings_order_id_fkey'), 'driver_ratings', 'orders', ['order_id'], ['id'])
    op.create_unique_constraint('_order_client_uc', 'driver_ratings', ['order_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_order_client_uc', 'driver_ratings', type_='unique')
    op.drop_constraint(op.f('driver_ratings_order_id_fkey'), 'driver_ratings', type_='foreignkey')
    op.drop_column('driver_ratings', 'order_id')
    # ### end Alembic commands ###
