"""Convert lat/long to numeric

Revision ID: a998a8d421f7
Revises: 4ff61f9b0695
Create Date: 2025-08-02 14:07:49.077480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a998a8d421f7'
down_revision: Union[str, None] = '4ff61f9b0695'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'pickup_latitude',
               existing_type=sa.VARCHAR(), # Assuming previous type was VARCHAR
               type_=sa.Numeric(precision=9, scale=6),
               existing_nullable=True)
    op.alter_column('orders', 'pickup_longitude',
               existing_type=sa.VARCHAR(), # Assuming previous type was VARCHAR
               type_=sa.Numeric(precision=9, scale=6),
               existing_nullable=True)
    op.alter_column('orders', 'dropoff_latitude',
               existing_type=sa.VARCHAR(), # Assuming previous type was VARCHAR
               type_=sa.Numeric(precision=9, scale=6),
               existing_nullable=True)
    op.alter_column('orders', 'dropoff_longitude',
               existing_type=sa.VARCHAR(), # Assuming previous type was VARCHAR
               type_=sa.Numeric(precision=9, scale=6),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'dropoff_longitude',
               existing_type=sa.Numeric(precision=9, scale=6),
               type_=sa.VARCHAR(), # Reverting to VARCHAR
               existing_nullable=True)
    op.alter_column('orders', 'dropoff_latitude',
               existing_type=sa.Numeric(precision=9, scale=6),
               type_=sa.VARCHAR(), # Reverting to VARCHAR
               existing_nullable=True)
    op.alter_column('orders', 'pickup_longitude',
               existing_type=sa.Numeric(precision=9, scale=6),
               type_=sa.VARCHAR(), # Reverting to VARCHAR
               existing_nullable=True)
    op.alter_column('orders', 'pickup_latitude',
               existing_type=sa.Numeric(precision=9, scale=6),
               type_=sa.VARCHAR(), # Reverting to VARCHAR
               existing_nullable=True)
    # ### end Alembic commands ###
