"""create_driver_ratings_table

Revision ID: ca88e4cbf893
Revises: 8c9f1a2b3d4e
Create Date: 2025-10-06 04:55:43.673949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'ca88e4cbf893'
down_revision: Union[str, None] = '8c9f1a2b3d4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('driver_ratings',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('driver_id', sa.String(), nullable=False),
        sa.Column('client_id', sa.String(), nullable=False),
        sa.Column('rating', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
        sa.ForeignKeyConstraint(['driver_id'], ['drivers.driver_id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # The following foreign key changes were autogenerated but seem spurious, removing them.
    # op.drop_constraint(op.f('payments_order_id_fkey'), 'payments', type_='foreignkey')
    # op.create_foreign_key(None, 'payments', 'orders', ['order_id'], ['id'])
    # op.drop_constraint(op.f('refunds_order_id_fkey'), 'refunds', type_='foreignkey')
    # op.drop_constraint(op.f('refunds_payment_id_fkey'), 'refunds', type_='foreignkey')
    # op.create_foreign_key(None, 'refunds', 'orders', ['order_id'], ['id'])
    # op.create_foreign_key(None, 'refunds', 'payments', ['payment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('driver_ratings')
    # The following foreign key changes were autogenerated but seem spurious, removing them.
    # op.drop_constraint(None, 'refunds', type_='foreignkey')
    # op.drop_constraint(None, 'refunds', type_='foreignkey')
    # op.create_foreign_key(op.f('refunds_payment_id_fkey'), 'refunds', 'payments', ['payment_id'], ['id'], ondelete='CASCADE')
    # op.create_foreign_key(op.f('refunds_order_id_fkey'), 'refunds', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    # op.drop_constraint(None, 'payments', type_='foreignkey')
    # op.create_foreign_key(op.f('payments_order_id_fkey'), 'payments', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
