"""Add payments and driver_payouts tables

Revision ID: cb3177d0e158
Revises: 5274b142cf82
Create Date: 2025-11-05 10:57:14.532530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cb3177d0e158'
down_revision: Union[str, None] = '5274b142cf82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('driver_payouts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('driver_id', sa.String(), nullable=False),
    sa.Column('request_id', sa.String(), nullable=False),
    sa.Column('payout_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payout_date', sa.DateTime(), nullable=True),
    sa.Column('payout_status', sa.Enum('REQUESTED', 'APPROVED', 'DISBURSED', 'FAILED', name='payoutstatus'), nullable=True),
    sa.Column('payment_request_ref', sa.String(), nullable=True),
    sa.Column('disbursement_method', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('driver_ratings')
    # Add new columns as nullable first
    op.add_column('payments', sa.Column('client_id', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('request_id', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('payment_date', sa.DateTime(), nullable=True))

    # Populate client_id and request_id from existing data
    # Assuming user_id maps to client_id and order_id maps to request_id
    op.execute("UPDATE payments SET client_id = user_id WHERE client_id IS NULL")
    op.execute("UPDATE payments SET request_id = order_id WHERE request_id IS NULL")

    # Now make them not null
    op.alter_column('payments', 'client_id', nullable=False)
    op.alter_column('payments', 'request_id', nullable=False)

    op.alter_column('payments', 'payment_method',
               existing_type=postgresql.ENUM('CREDIT_CARD', 'MOBILE_MONEY', 'CASH', 'OTHER', name='paymentmethod'),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index(op.f('ix_payments_transaction_id_unique'), table_name='payments', postgresql_where='(transaction_id IS NOT NULL)')
    op.drop_constraint(op.f('payments_order_id_fkey'), 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'users', ['client_id'], ['id'])
    op.create_foreign_key(None, 'payments', 'orders', ['request_id'], ['id'])
    op.drop_column('payments', 'order_id')
    op.drop_column('payments', 'transaction_details')
    op.drop_column('payments', 'payment_type')
    op.drop_column('payments', 'user_id')
    op.drop_column('payments', 'gateway')
    op.drop_column('payments', 'currency')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('payments', sa.Column('gateway', postgresql.ENUM('PAYFAST', 'PAYSTACK', name='paymentgateway'), server_default=sa.text("'PAYFAST'::paymentgateway"), autoincrement=False, nullable=True))
    op.add_column('payments', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('payments', sa.Column('payment_type', postgresql.ENUM('CLIENT_PAYMENT', 'DRIVER_PAYMENT', name='paymenttype'), autoincrement=False, nullable=False))
    op.add_column('payments', sa.Column('transaction_details', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('payments', sa.Column('order_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key(op.f('payments_order_id_fkey'), 'payments', 'orders', ['order_id'], ['id'])
    op.create_index(op.f('ix_payments_transaction_id_unique'), 'payments', ['transaction_id'], unique=True, postgresql_where='(transaction_id IS NOT NULL)')
    op.alter_column('payments', 'payment_method',
               existing_type=sa.String(),
               type_=postgresql.ENUM('CREDIT_CARD', 'MOBILE_MONEY', 'CASH', 'OTHER', name='paymentmethod'),
               existing_nullable=False)
    op.drop_column('payments', 'payment_date')
    op.drop_column('payments', 'request_id')
    op.drop_column('payments', 'client_id')
    op.create_table('driver_ratings',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('driver_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('order_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], name=op.f('driver_ratings_client_id_fkey')),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.driver_id'], name=op.f('driver_ratings_driver_id_fkey')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('driver_ratings_order_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('driver_ratings_pkey')),
    sa.UniqueConstraint('order_id', name=op.f('_order_client_uc'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('driver_payouts')
    # ### end Alembic commands ###
